### ISSUE TITLE
192x64 Ghosting

### ISSUE THREAD

**Issue by Bandicoot37** [lucky01/PIN2DMD#11]
hello
 i'm using a pin2dmd with last firmware XL and i got some strange ghosting
https://streamable.com/bi3g6u

i try the 2.68 firmware and realy better but sometime got a problem look at the "s" at the end of this video and "ins" of insert coin ghost a little 
https://streamable.com/ffy2ph
thanks if you can help me :) :)

**Comment by lucky01** [comment]
fixed in v3.13
