### ISSUE TITLE
DLL Versioning

### ISSUE THREAD

**Issue by skyblaster** [lucky01/PIN2DMD#12]
Would it be possible to add additional properties to your dmddevice DLLs in an effort to get it to play nice with PinballY from @mjrgh?
http://mjrnet.org/pinscape/PinballY.php#dmddeviceDLL

Currently seeing the following in PinballY:
```
+ retrieving file version info for DLL, to check for special handling
++ DLL version info not available; we must assume this is an old version with known bugs, so some
   features will be disabled.  Please update your DmdDevice.dll to a current version.
```

**Comment by lucky01** [comment]
I added a version string to the latest dmddevice.dll.
