### ISSUE TITLE
PIN2DMD-XL 3.13 stop working with color rom

### ISSUE THREAD

**Issue by Bandicoot37** [lucky01/PIN2DMD#13]
Hello
I try some colored rom 128x32 and every time it freeze after 10 secondes ( communication is lost and need to reset NUCLEO ) , no probleme when it's not colored.
I test to flash my NUCLEO with non XL firmware , and it doesn't freeze

PS : No probleme with 192x64 colorised roms
thanks

**Comment by lucky01** [comment]
Please ask colorization Support Questions on the Forum

**Comment by Bandicoot37** [comment]
it's not a problem with the colorised rom i think , cause with the non XL firmware it's working ( display isn't good due to the matrix but it doesn't freeze )

**Comment by lucky01** [comment]
I read your text several times and it did not make any sense until I understood that you are using a XL display in visual pinball mode. You should add such information when you open a issue. Which dmddevice.dll are you using ? Although I think you are the only one who uses this configuration we should move this issue over to the vpuniverse forum as a documetation for other users. Please open a thread there and I will join in.
