### ISSUE TITLE
Idea to help diagnose SD Card file read problem

### ISSUE THREAD

**Issue by madnat** [lucky01/PIN2DMD#14]
Some users report a SD card is not being read by the PIN2DMD display.  Sometimes this is true, sometimes it is due to bad file names on the SD card.

Could a menu option be added to list current files loaded by the display, and list files found on the SD card?

**Comment by lucky01** [comment]
I see no real usecase for such a menu option. The function of the SD reader can easily be tested by inserting a blank sd card and initiating a config save which should create a pin2dmd.dat on the SD.

**Comment by madnat** [comment]
Many real Pinball users are not PC savvy,  dont have multiple SD cards, and therefore are tricky to help.  Some users suggest SD cards larger than 32GB are not read by the PIN2DMD display unit - which I cannot verify/validate.  So would help these people.

**Comment by lucky01** [comment]
If they are are not PC savvy, how do they copy the colorization they want to use to the SD card ?

**Comment by lucky01** [comment]
I assume you test the function of the SD reader before you ship the boards.
Adding a function like listing the files on the SD is not somthing you add in a couple of minutes.
What I could add in a future version is something like create, write and read and delete a dummy file
but currently I have different projects.

**Comment by madnat** [comment]
Many options for a non PC savvy pinball owner get a SD card installed when fitting a PIN2DMD display, 

1.  Have a helpful community members (like me) organise the SD card with files from the author, 
2. have a family member or friend help the pinball owner get the display installed, 
3. pay a technician to install a colour DMD into their real pinball

**Comment by lucky01** [comment]
All 3 options include a person who is able to check the function as described above.

**Comment by madnat** [comment]
There is no expectation that this feature would be added immediately.  Simply feedback on how we can make the product easier to use for non-technical people.  If it isnt something that can be done - then no issue.  Simply trying to help people who have the display - and have trouble getting it going very occassionally.

**Comment by madnat** [comment]
On the test point - there is no exitsing feature to test if the display is reading the SD card without fitting the display to the real pinball machine - that I'm aware of.  That would help solve the problem for scenario 1 (help from an author or community member create a SD card for the real pinball owner).

Perhaps a simple display of:
.PAL read Yes/No and .FSQ read YES/NO would be easier to implement - and serve the same need?

Just suggestions

**Comment by lucky01** [comment]
You can test wether the SD is working properly by initiating a save config - remove the SD card - change a setting like devicemode, palette, brightness and save config. After you reinsert the SD card and reboot your last config change should be overwritten by the last version on the SD card.

**Comment by lucky01** [comment]
> .PAL read Yes/No and .FSQ read YES/NO would be easier to implement - and serve the same need?

I consider implementing something like this in a future version.
