### ISSUE TITLE
Feature Request: Timecode Overlay on Pin2dmd screen from Editor

### ISSUE THREAD

**Issue by Happymealtm** [lucky01/PIN2DMD#15]
Add in "debug" menu to the Pin2dmd firmware with a "timecode overlay" feature. Enabling this option on the Pin2dmd device would add a timecode that is seen in the editor window down the bottom to be overlayed onto the display and would be the same code as shown in the editor. Give the user a few positions to overlay if they are working on a bug in a certain area they can move the timecode so it will not cover the screen. (Left right etc) The timecode will not be captured in the dump on the image it will just be for recording off the screen where if the user can't overlay a timecode using their own device it will come in handy. It will also make it easier to sync the recording if you don't hit the start on both devices at the same time or if there is a delay or for people who can't sync it up easily.

For Data East x16 it could be put inside the blank areas to be used with back glass off.

Great for quickly troubleshooting if you have a large dump file and need to get to areas quickly.

This may be more for the Firmware than the editor but they would have to sync up anyway so it would be need to be linked to both FW and editor to make sure it will work.

**Comment by lucky01** [comment]
There is no dump recording function in the editor, so I don´t know what you are talking about. Also adding information to the display during operation will add a additional delay in frame processing, which will cause frame drops in the dump. That is also the reason why it is recommended not to have a colorization active during a creation of a dump using the pin2dmd.exe tool. Sorry I have to reject that feature request for many technical reasons.
