### ISSUE TITLE
Need to reset on boot with latest Nucleo STM firmware

### ISSUE THREAD

**Issue by arnoz26** [lucky01/PIN2DMD#16]
Hello there
I've upgraded my Nucleo f429 firmware to latest with stm utility (2-37-27), then device did not boot properly, i need to reset it to view it on windows.
Need to downgrade to 2-32.M22 to have my pin2dmd work properly.

Any info on that issue ?

**Comment by lucky01** [comment]
http://vpuniverse.com/forums/topic/4582-bug-in-st-link-firmware-v2j36m26/

This is not a pin2dmd bug but a bug in the ST-Link firmware. There is nothing I can do about it.

**Comment by rgiot** [comment]
Sorry to comment this closed issue; but is it possible to indicate that in the documentation ? On the installation page, the sentence "!! Note :If your device does not start the PIN2DMD firmware when powered up your Discovery or Nucleo boards may need a ST-Link firmware update from here" is misleading. 

Bests
