### ISSUE TITLE
Few 5V and GND routing issues in the new 256x64 EVO design

### ISSUE THREAD

**Issue by Stumblor** [lucky01/PIN2DMD#19]
Could just be my conversion of the eagle file, but just thought I would raise in case these haven't been picked up already.

5v:

![image](https://user-images.githubusercontent.com/3416626/122637794-78a4fa00-d0e8-11eb-8091-e8588f3fd2e1.png)

GND:

![image](https://user-images.githubusercontent.com/3416626/122637813-88244300-d0e8-11eb-81da-efab3e4204f6.png)

GND:

![image](https://user-images.githubusercontent.com/3416626/122637829-95d9c880-d0e8-11eb-86b8-eef450310bdb.png)

**Comment by lucky01** [comment]
You are right with the missing 5V trace but the GND does not show up in my version. I uploaded a updated version
