### ISSUE TITLE
Using vpinmame as source, Pin2dmd Hangs during playback

### ISSUE THREAD

**Issue by comicalman** [lucky01/PIN2DMD#2]
I have created another test project.  This time, I used a dump from vpinmame directly.
When I try it, the display hangs - right at my first replacement frame and requires me to restart the display altogether.

see the project- named Xfiles_v4m1.xml located at this post:
http://vpuniverse.com/forums/topic/2268-pin2dmd-editor/?p=30042

**Comment by lucky01** [comment]
I forwarded this issue to 
https://github.com/sker65/
who is responsible for the editor
