### ISSUE TITLE
What's dmdext.dll?

### ISSUE THREAD

**Issue by freezy** [lucky01/PIN2DMD#20]
Hey,

It looks like you're bundling dmdext's `DmdDevice.dll` as `DmdExt.dll` in your dmddevice.zip [here](https://github.com/lucky01/PIN2DMD/tree/master/integration/pinmame). I suppose that's a proxy that uses your own dmddevice implementation for PIN2DMD and falls back to dmdext for other outputs like LCDs?

Since dmdext also supports PIN2DMD, what's the reason for this? It's a bit confusing and looks like a GPL violation to me.

**Comment by lucky01** [comment]
GPL violation ? The source of dmdext.dll is here https://github.com/lucky01/dmd-extensions/tree/dmdext.dll
I use the colorization code in my dll and pass the frames as RGB24 to your DLL.
It is all described here https://vpuniverse.com/forums/topic/7191-new-version-pin2dmd-dmddevicedll-with-dmdext-as-plugin/

**Comment by pinballpower** [comment]
As the colorisation code is not GPL licensed, you're not allowed to link it into GPL 2.0 code.

**Comment by freezy** [comment]
Thanks for the link, I just came back from holidays and didn't catch up with everything at the forums yet.

For the GPL, as @pinballpower said, if you ship software that loads GPL code, your software must be GPL as well.

**Comment by lucky01** [comment]
My dll does not depend on the dmdext.dll . It also works without it, with the limitation to pin2dmd devices only. I pass the colorized frames to GPL 2.0 code just like pinmame does, which is also distributed with freezy and not licensed under GPL. Btw the dmddevice.dll interface API freezy uses to connect to pinmame was contributed to the pinmame code by myself. I just added dmdext.dll for the convience of desktop users which use a virtual display. I could also distribute it seperately if you feel better then.  Additionally there are two different opinions about this :

Does the use of GPL'ed DLLs f in your program need you to release your program under GPL too?

There seem to be two different strands of opinion. The [FSF](http://www.fsf.org/) holds that dynamic linking creates a derivative work, and so any program designed to run with a GPL-ed DLL, must be GPL itself; see http://www.fsf.org/licenses/gpl-faq.html. The only exception they make is for DLL's that come with the compiler and the kernel, such as the MS VC run-time DLL's; see http://www.fsf.org/licenses/gpl-faq.html#WindowsRuntimeAndGPL. On the other hand some OpenSource lawyers hold that dynamically linking does not make your program GPL; see http://www.nusphere.com/products/library/gpl_0401openmag.pdf and the discussion in http://www.linuxjournal.com/article.php?sid=6366. There is no doubt that programs that link dynamically to DLL's from libraries with the [LGPL](http://www.gnu.org/copyleft/lesser.html) or with the GPL with [special provisions](http://www.gnu.org/licenses/gpl-faq.html#TOCLinkingOverControlledInterface), are GPL free if you decide so.

**Comment by freezy** [comment]
Both your URLs point to 404s.

I don't think it's relevant whether the commercial software works without the GPL software or not. It's the fact that you *distribute* it along with it. 

Not being able to be linked to commercial software is pretty much the point of the GPL. Otherwise everybody would just wrap GPL code into an open sourced wrapper and be done with it.

**Comment by lucky01** [comment]
Like I said, the same DLL is distributed with pinMame which is also not GPLv2

The coloring code in Freezy is based on the sources I provided you with the email topic "Top Secret" so IMHO your work should never have been published under GPLv2. But it is like it is now.

Here is a working link to the articles

https://web.archive.org/web/20060618213144/http://www.nusphere.com/products/library/gpl_0401openmag.pdf

https://web.archive.org/web/20061103081641/http://www.linuxjournal.com/article/6366

Here is the key sentence from my POV
Simply passing data between two programs, even if that data influences the behavior of the programs, does not create
a derivative work of either program.

**Comment by freezy** [comment]
1. It's not distributed with PinMAME, it's part of the all-in-one installer of VPX, which is another project, and that doesn't give you, or anyone else, any legitimization.
2. You always knew in advance that dmdext was GPL, and that the coloring port would be distributed as such. Claiming it "should never have been published" is dishonest, and frankly disappointing.
3. It's not about passing data or derivative work. It's about shipping GPL code along with commercial software.

**Comment by lucky01** [comment]
1. Of course it is no legitimization. I´m just wondering how this O.K. for your while you are complalning here.
2. As far as I remember one of your personal motivation in those days were to make the colorizations work on your private pindmdV3 from VirtuaPin. 
3.  How is the zip file and the software in it commercial in any kind ? The sole purpose of this package is to give the vpin users with virtual dmd, pin2dmd  or even pindmdV3 easy access to the latest colorization files.

**Comment by freezy** [comment]
1. Then don't sell it as an argument. It should be clear by now why I'm bringing it up here and not for the installer.
2. Sure. Mine and countless others. Not sure however why you're bringing up *my* motives when we were talking about *yours* (i.e. why you would even contact me to port your coloring code into a GPL software, if you didn't want the port to be GPL).
3. Replace "commercial" with "non-GPL", it applies all the same.

**Comment by lucky01** [comment]
GPL violation ? Sources are here 
https://github.com/lucky01/dmd-extensions/tree/dmdext.dll

It uses my own colorization code and forwards the data as rgb24 to all devices supported by dmdext.dll.

See https://vpuniverse.com/forums/topic/7191-new-version-pin2dmd-dmddevicedll-with-dmdext-as-plugin/
