### ISSUE TITLE
Reset problem with last bootloader 

### ISSUE THREAD

**Issue by saddys** [lucky01/PIN2DMD#22]
With new núcleo board there are the reset problem. Can someone share the (V2.J34.M26) stlink upgrades or a work bootloader? On st.com site there are only the last. Thanks

**Comment by lucky01** [comment]
This is not a pin2dmd issue. 
https://vpuniverse.com/forums/topic/4582-bug-in-st-link-firmware-v2j36m26/
Maybe better ask on vpuniverse.com
