### ISSUE TITLE
devicedmd.dll version

### ISSUE THREAD

**Issue by julianmiguel** [lucky01/PIN2DMD#23]
Hello Lucky
i have something strange 
I'm using PIN2DMD Version 4.44

I'm using Your deviceDMD.DLL working well for pac files.
But this dll is not working for Pinup popper (works with an other dll) and not working with deadpool vpx table
do you know if it is possible to select from a script the good deviceDMD.Dll working ?

Is it possible to downngrade my pin2dmd firmware ?
thanks a lot

**Comment by lucky01** [comment]
This DLL is only tested with pinmame where the dmddevice.dll interface was
introduced by me.
If other programs like pinup popper use that api but use improper
initialization like sending empty game name or
deadpool using non standard DMD resolution (128x16,128x32,192x64,256x64)
the problem should be fixed on their side.
Alternatively you can try this DLL which is extensively tested and has been
reported to be working well.
https://vpuniverse.com/forums/topic/7504-new-version-dmd-extensions-with-pin2dmd-coloring-plugin-and-pac-file-support/
Please understand that I don´t have the time to give one on one support for
specific VPin setups.
If you need further support please use the power of the community in forum.

You can downgrade your pin2dmd firmware using the upd file, but it is
always recommended to update to the latest version.
So far no issues have been reported with the latest version.


Am Sa., 11. Feb. 2023 um 15:05 Uhr schrieb julianmiguel <
***@***.***>:

**Comment by julianmiguel** [comment]
thanks for all thoses informations
i have test all you dmddevice.dll version and the problem start after the 24/04/22
it is just when you start to encaps all dll in a zip package
do you know what change between those versions 
thanks a lot

**Comment by lucky01** [comment]
I worked a lot on the dmdext integration which now has been replaced by the plugin DLL I linked above.
Try that version. It should solve the issues you currently have. Like I said my dmddevice.dll is only tested with the rom emulations in pinmame.
