### ISSUE TITLE
Updating x32 Firmware to 4.50 via .upd file can cause settings to change

### ISSUE THREAD

**Issue by Terranigma1** [lucky01/PIN2DMD#24]
I have had a few instances where updating firmware from older versions to 4.50 on x32 EVO units will change config settings.

Sometimes it will change the RGB sequence or device (or both). For the most part a .dat file is not on the SD card before the update is copied across, so it seems to be separate to that. Most of the updates with issues have been from 4.49 to 4.50. I have tried different SD cards and new downloads of the firmware but it seems to still occur, although still randomly.

I have only noticed this since updating to 4.50, so I am not sure if it is present before in earlier versions but I have not seen it myself. Original firmware has also been flashed via different methods before the update, I believe the STM programmer and also DFUSE, possibly a few using the pin2dmd app as well. 

Could you please look into it and see if there is anything that would cause this to happen?

Thanks

**Comment by lucky01** [comment]
Looking at the code changes made from 4.49 to 4.50 I can not see anything that could cause this to happen.
Unless you find a way to make this issue reproduceable unfortunatelly there is nothing I could do about it.
