### ISSUE TITLE
Firmware compatibility of custom boards

### ISSUE THREAD

**Issue by VaderMester** [lucky01/PIN2DMD#25]
Hi,

I was updating some custom boards to the latest 4.51 FW and it no longer works.
**Last version known to work: V4.41**

I'm using the Nucleo-144 FW as it is for custom boards, I've been using the Nucle FW for a while, and it was working on custom boards.

I checked to see exactly which version stops working.
V4.41 was the last version to work on my custom boards.
All my custom boards are based on Nucleo-144 V4 schematic. They use F429ZIT6 and F407VET6 and F407VGT6 CPUs.
V4.41 works on all of them, **from V4.42 none of them works.**
I would accept if it would not work on a F407, but it is also not working on an F429ZIT6m which is the exact same chip as on the Nucleo-144.

Symptoms: No picture, and USB detection on Windows also fails.

Can you give me any idea which FW to use on custom boards from V4.42?

**Comment by lucky01** [comment]
https://pin2dmd.com/hardware/#2.4

**Comment by lucky01** [comment]
Hey Bence,

on behalf of the children with cancer and from the orphanage where the pin2dmd donations go to I congratulate you that you found a way to crack the pin2dmd fimware to sell it again in your shop without making a single donation.

You are a true hero !

**Comment by VaderMester** [comment]
Hi Lucky01!

I'm surprised to read these allegations, and I am wondering what made you
think that I am involved in the actions you described.
Can you please send me a picture of the PCB you think has cracked FW? I
would like to make sure it is not my design, as I would not like to be a
part of any of it.

I would like to be as transparent with you as possible.

I assume here you referring to the PCBs made by Pirategames.
I am not involved with their business, I'm only a freelancer individual
entrepreneur, who - as a hobby - designs PCBs for various customers, them
included.
This is a part time job, and the only thing I do is design, and build the
PCBs by hand.
Fun fact: I don't not even own the designs I make for them as per contract,
and I do not get any shared profits for the sales. My contractual
obligations end with the shipping of the last PCB, and until the warranty
period is over.

I was aware that a cracked PCB existed, but it was not my design and build.
All I know is that it is a red PCB (it is also appears on your page), but
as I heard the person who made those boards and FW crack, actually passed
away last year. He was in his 50s as I know and died of brain hemorrhage.

I have only designed a blue colored PCB for them, which was based on the
Nucleo144 design and FW. It is a blue PCB with two CPU footprints on the
board to have the ability to take both 100pin and 144pin packages.
As I remember only 20 PCBs have been made, but all of them were licensed by
you, so fully legal apart from the custom design, the last batch was in
summer 2022.

There was another batch in the plan in 2023, but that was when I discovered
that there is no longer support for custom PCBs (hence the Github issue
posted), so I did not make them in the end.

I was planning on releasing a PCB to the community, that has several nice
features, like 5V ESD protection diodes, reverse voltage protection on the
supply, the Option button being combined with the Boot0 pin to allow FW
upload with USB, and without the need of an ST-Link, and of course the dual
CPU footprint setup, so you can essentially use any CPU from F407 to F429
and F427, in case chip shortage is an issue. Your custom FW has been tested
on F429, F427 CPUs, and F407VET6 and F407VGT6 MCUs, so it is a pretty good
candidate to allow more people to use a nice design.
Also, included with the PCB design, I designed a power board to convert any
voltage from 9V to 36V to 5V, made in a way that it can be soldered to the
PCB, so you can decide if you need it or not.

It is not ready yet, because - A: I am swamped right now due to me
attending University on weekends to complete my MSc course, - B:  You
stopped support for custom PCBs.
I was hoping to make a deal with you on this, once I have time to finish
it, but after your accusations, I think these hopes are short lived.
In any case if all goes well, I will contact you later this year, so that I
can send a prototype of the design, and from that point it is up to you to
do whatever you want with that.
Most of these extra features have been tested already, but the power module
needs some extra filtering as it has a few low amplitude switching spikes
on the output, which I do not like, but after it is fixed I would be ready
to post it.
The PCB also needs some modifications, and some kind of branding (You name
your board Nucle, EVO, so I'll add a design name to it also), so I would
not violate the copyright of my previous design, which now is owned by
Pirategames. I would like to avoid trouble as much as possible.

*Bujtor Bence*

*Individual Enterpreneur*
Electrical engineer
------------------------------------------------------------
📧   ***@***.***
📱       +3670-947-5173
