### ISSUE TITLE
Unable to connect to PIN2DMD

### ISSUE THREAD

**Issue by ptroost68** [lucky01/PIN2DMD#26]
i bought a virtual pinball cab with a Pin2dmd device installed.  i rebuilt the computer and have a clean install of Windows 11 but cannot connect to the device with ST-LINK software or Pin2dmd utility.  it lights up and says "Pin2dmd virtual pinball'

i have replaced the USB driver as instructed.

In device manager it says "libusb-win32 devices" and lists "ST-Link Debug (Interface 0)" and "ST-Link VCP Ctrl (Interface 2)"

I can't find any tutorials or debugging advice to get this working with virtual pinball

thank you!

**Comment by lucky01** [comment]
Please ask all support questions in the vpuniverse forum or check Pin2dmd.com. I don't have time for one on one support. You probably use the wrong usb port on the controller Am 25.10.2023 um 01:14 schrieb ptroost68 ***@***.***>:﻿
i bought a virtual pinball cab with a Pin2dmd device installed.  i rebuilt the computer and have a clean install of Windows 11 but cannot connect to the device with ST-LINK software or Pin2dmd utility.  it lights up and says "Pin2dmd virtual pinball'
i have replaced the USB driver as instructed.
In device manager it says "libusb-win32 devices" and lists "ST-Link Debug (Interface 0)" and "ST-Link VCP Ctrl (Interface 2)"
I can't find any tutorials or debugging advice to get this working with virtual pinball
thank you!
