### ISSUE TITLE
SYSXDMD segments missing issue

### ISSUE THREAD

**Issue by TonySV6** [lucky01/PIN2DMD#27]
Hello and thank you for the great hardware. I have an issue with some games and I tried everything to fix.
My game swords of fury only works on the DE setting. It’s almost perfect but the bottom row is missing some segments. I think because it is 2x alpha and swords is alpha and numeric. The wpc setting is all wrong.
One other small problem is Whirlwind. It has the very last character missing some segments. I have attached pictures to show.

![Swordsde](https://github.com/lucky01/PIN2DMD/assets/173465982/b068d3fb-4b7e-4fde-8d7b-89bf0aef0fd1)

![swordwpc](https://github.com/lucky01/PIN2DMD/assets/173465982/0c82030c-d1a3-4514-9577-e1c6ca4bfc14)

![swordattarde](https://github.com/lucky01/PIN2DMD/assets/173465982/430ee7fe-a8da-4862-866f-e236bb68b514)

**Comment by TonySV6** [comment]
This is Whirlwind...

![ww](https://github.com/lucky01/PIN2DMD/assets/173465982/80fe823d-6447-41a3-9016-89a3e817a0a5)

**Comment by lucky01** [comment]
In fact the first test was done on a whirlwind, and if you look at the
video here
https://www.youtube.com/watch?v=C3NiMk1XTwA
there seems no missing segment problem.
I assume it is a hardware issue either cabeling or a missing connection on
your sysxdmd board.



Am Fr., 21. Juni 2024 um 22:40 Uhr schrieb TonySV6 ***@***.***

**Comment by TonySV6** [comment]
I have tried all 3 different cables, and all 5 of my boards and all with the same issue.
And sorry, I shouldn't have said segment. It's not the whole segment, just a few dots of the last segment.
In your video, it actually doesn't have a number or letter with the missing dots, so you can't see the issue in that video.
On Whirlwind, it's only 3 dots missing on the last segment, but the 3 inside dots on the numbers 2, 3, 5, 6 and 8.
If you check it in display test mode, you can see the missing dots.

And on my Swords of Fury, the missing dots is on the entire bottom row, not just the last segment.

You can see the 0 doesn't show it, but the 5 does.

Whirlwind display test...

![IMG_6660](https://github.com/lucky01/PIN2DMD/assets/173465982/a18e49f6-ea39-4cf2-aba2-e94158650fb5)

![IMG_6664](https://github.com/lucky01/PIN2DMD/assets/173465982/6186ad72-9c14-4f49-b9f2-4b1da401431d)

**Comment by lucky01** [comment]
O.K. This will take some time. I need to setup a Whirlwind CPU on the bench
to test and debug this.
Will return to you with the result.

Am Sa., 22. Juni 2024 um 08:59 Uhr schrieb TonySV6 ***@***.***

**Comment by lucky01** [comment]
I had a quick look at the code and it seems to be a timing issue. I will see if I can add a parameter to make the timing adjustable.

**Comment by TonySV6** [comment]
> I had a quick look at the code and it seems to be a timing issue. I will see if I can add a parameter to make the timing adjustable.

Great! If you need anymore information from me, just let me know.

**Comment by lucky01** [comment]
I have uploaded a new version. Please test !

**Comment by lucky01** [comment]
According to Pinmame Swords should look like this
![swrds](https://github.com/lucky01/PIN2DMD/assets/14914346/750c1151-d2ff-4797-a96b-302c571fc73f)

**Comment by lucky01** [comment]
I think I need to add 2x7Alpha + 2x7Num as a display layout for that.

**Comment by TonySV6** [comment]
I tested my Whirlwind with the new update and it's working great now! Thanks!!

For Swords of Fury, I select WPC 2x Alpha 2x Numeric mode in settings and nothing looks right :/ The characters look all nonsense.
But, if I put it in the DE 2x alpha mode it works, but then the bottom line is wrong. Could it be because there is no numeric setting for this?
Maybe if you added a DE 2x 7 alpha 2x 7 numeric that could work?

**Comment by lucky01** [comment]
I just uploaded v1.02 which adds WPC 2x7alpha 2x7num as display mode to display swords correctly.

**Comment by TonySV6** [comment]
I just got a chance to test it now and it works! Yay.
Whatever the problem was, it is now fixed, Looks good.
I'll do some more thorough testing, but from what I've seen, it looks like it's working so far.
Thank you!
