### ISSUE TITLE
Cant read at address 0x0000 in some tables 

### ISSUE THREAD

**Issue by dizzeee** [lucky01/PIN2DMD#3]
Hi,

really love Visual Pinball X and the opportunity to use my Pin2DMD with the dmddevice.dll and stuff.
A lot of tables are working great, but some won´t start every time. These Tables are for example, 24, CFTBL, Family Guy and others.

I´ve included the Crash-Dump from VPX and a screenshot of the Windows-Crash-Prompt.

Installed is newest VPX-Beta with latest SAM-Build of Vpinmame with latest dll´s

Would be really happy to hear a possible solution.

![fehler](https://user-images.githubusercontent.com/39675456/40588157-944a2aea-61d9-11e8-8656-cc0694c5a9e0.PNG)

[crash.txt](https://github.com/lucky01/PIN2DMD/files/2042787/crash.txt)

**Comment by lucky01** [comment]
This problem is not related to pin2dmd. Please report to the VPX dev team or ask for help in the forums
