### ISSUE TITLE
activation key

### ISSUE THREAD

**Issue by ninfan** [lucky01/PIN2DMD#4]
Hello,
Can't find informations about activation Key on the pin2dmd.com webside?
Also on vpuniverse i found no informations.

May it be possible to get all infos here on git or your website?
Its like a alleycat.

**Comment by lucky01** [comment]
On pin2dmd.com it says under point 2 "Firmware"
"Instructions how to install, update or ACTIVATE the firmware"

If you follow the link you get to
https://pin2dmd.com/installation/
and there under point 3 you find all you need.

And on VPU 
http://vpuniverse.com/forums/topic/2436-pin2dmd-colorprism-v20-firmware/
I wrote
"For the rest, we kindly request to send your UID and username with the donation link in my signature below."
