### ISSUE TITLE
PIN2DMD does not recognize

### ISSUE THREAD

**Issue by tcharlie84** [lucky01/PIN2DMD#5]
Hi,

I recently acquired some PIN2DMD cards through your project and received them recently from the indicated company that produced them for me.

I performed the welds on the back of the pcbs with the display connectors and plugged the ribon cable between the two displays.

Now I'm trying to install the firmware but I'm not succeeding.

I do not get any images on the displays, it only gets black screen.

The mini USB cable when connecting to the EVO card I get no connection signal in Windows 10 and it seems that I do not get any light on the EVO data board, except for a single power light,
5V.

In device manager the PIN2DMD is not recognized, and there is no notification when plugging or unplugging the mini USB cable.

I tried the installation via ST-LINK Utility and also through DfuseDemo, but the two programs do not recognize any device.

I also tried to click on the DFU button that has on the board to try some recognition but no signal.

In the .exe zaddig program I also can not find the device because I do not seem to recognize.

I have attached on the back of my Evo PIN2DMD only the micro USB, formatted USB card and the 5V power supply.

Attached follows a google drive of the images of how the connections are.

What can I be doing wrong?

Please, your help is very important to me!

Cheers!

https://drive.google.com/open?id=1IWZ0EjIJ1ze4cFkS0NusCTcBQm2tkYc5

**Comment by lucky01** [comment]
Hold down the DFU button and press/release the reset button. DFU button is only checked during startup of the processor. Installation procedure is described here https://pin2dmd.com/installation/
