### ISSUE TITLE
STM32F4 Discovery v3 Schematic question

### ISSUE THREAD

**Issue by AussieMakerGeek** [lucky01/PIN2DMD#6]
Hi, First of all - Great work on the development of this platform. I built my VP cabinet about 6 years ago when a 'real' DMD was prohibitively expensive so I went with an LCD at the time.  Now I am rebuilding my cab with some new toys so looking at making one of these.

However, I am going over the schematic for the STM32f4 discovery and I am confused as to why it needs the Mini RTC as well as using the internal RTC? Or the external RTC is just used to set the internal RTC at power up? Or for that matter, why it needs an RTC at all?

Also, its not clear to me what the function of all of the external components are for such as the MAX232, ESP8266, IR and PIR - I know what all these devices do, just don't understand what function they provide for the DMD and if omitting them will prevent the base operation of the DMD.  Have I overlooked some documentation somewhere?

I can see the reason for the SD card but if it is only used for updates and registration (and we have alternative methods for these functions already), can it be omitted too?

**Comment by lucky01** [comment]
All the components you named can be omitted if you only want to use it for vpin.
RTC,PIR,WIFI,IR are for use with https://go-dmd.de/ . SD, LS123, MAX232 are for use with real pinball machines. I would install the buttons to have access the onscreen menu.

**Comment by AussieMakerGeek** [comment]
Awesome, thanks for clearing that up. Makes it extremely simple now!

Just confirming, that also means there is no need for external crystal and caps for the internal RTC?

**Comment by lucky01** [comment]
No ! RTC is not used with pin2dmd

**Comment by vhlh310177** [comment]
Hi. Excellent work. I have a question?. Sorry for my bad inglish. Its necesary use the shield with the STM32 Nucleo-144 STM32F429ZI, i only use this for a virtual pinball.

**Comment by AussieMakerGeek** [comment]
It's not, it just makes it a lot easier. I used a 'DiyMore' Stm32f4 board which is a minimalist board and a protoboard. It works fine but is not for someone without good experience with electronics and reading schematics. Mine just has connection to the led board 16 pim connector and 2 buttons for the menu.

**Comment by lucky01** [comment]
> It's not, it just makes it a lot easier. I used a 'DiyMore' Stm32f4 board which is a minimalist board and a protoboard. It works fine but is not for someone without good experience with electronics and reading schematics. Mine just has connection to the led board 16 pim connector and 2 buttons for the menu.

I have one of those boards here and although they say they use the STM32F407VGT6 (1MB Flash) a STM32F407VET6 is installed (512kb Flash). We will most likely use that additional 512kb flash memory in the future and that will break compatibility to the VET6 based boards. To make support and code maintainance as easy as possible for me, I will only make sure that my code runs on the hardware used by my designs (Disco, Nucleo429 and EVO boards). Anything else is on your own risk.

**Comment by AussieMakerGeek** [comment]
I totally understand that position, it is at your own risk of course if using a non-standard board. You cant be expected to support homebrew versions.

I have 2 of the DiyMore boards and both have vgt6 chips, not vet6. Or at least that is what is written on the chip.
