### ISSUE TITLE
EVO 128x32 not recogized by USB

### ISSUE THREAD

**Issue by azwakeboarder** [lucky01/PIN2DMD#8]
I just finished the EVO 128x32 build with the files provided, Thank you for your effort. I was able to flash the firmware using the st-link usb to header programming tool. The pin2dmd now turns on the shows the PIN2DMD banner. I requested the key off the number displayed. I have received the key but the Windows 10 machine does not recognize the device when using the mini-USB plug. I have tried zadig-2.4 utility and it does not show up as a usb serial device. Have any suggestions?

**Comment by lucky01** [comment]
PIN2DMD does not register as a serial device. It should autoregister as a generic winusb device under windows 10. No need to change the drivers with zadig unless you want to use old programs that rely on libusb32. If you hold down the dfu button during boot or reset it should register as a dfu device asking for drivers. In any other case you have either a software or USB problem. You can ask at vpuniverse.com forum for help.
